# Generated by Django 5.1.7 on 2025-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('roll', models.IntegerField(unique=True, verbose_name='Roll Number')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
            ],
        ),
    ]
