# Generated by Django 5.1.7 on 2025-03-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Name'),
        ),
    ]
