# Generated by Django 5.1.7 on 2025-03-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
